name: Build and Deploy
on:
    push:
        branches:
            - master
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            - name: Install Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.21.x

            - name: Install Protoc
              uses: arduino/setup-protoc@v1
              with:
                  version: 3.x
                  repo-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Install Protoc Go plugin
              run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

            - name: Install Node
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Checkout üõéÔ∏è
              uses: actions/checkout@v2.3.1

            - name: Build üîß
              run: |
                  make dist/cata/.dirstamp

            - name: Update proto version file
              run: |
                  cp sim/core/TestProtoVersioning.results .deployedprotoversion

            - name: Commit updated version file
              run: |
                  git config --local user.name "GitHub Actions"
                  git config --local user.email "actions@github.com"
                  if ! git diff --exit-code; then
                      git checkout -b github-actions
                      git add .deployedprotoversion
                      git commit -m "Auto-update .deployedprotoversion file due to API version increase"
                      git push --set-upstream origin github-actions
                      gh pr create --fill
                      gh pr merge --merge --delete-branch
                  fi
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Test
              run: |
                  make test

            - name: Deploy üöÄ
              uses: JamesIves/github-pages-deploy-action@4.1.5
              with:
                  branch: gh-pages
                  folder: dist/cata
                  single-commit: true
